data_cfg:
  dataset_name: Gait3D-Parsing
  dataset_root: your_path
  dataset_partition: ./datasets/Gait3D/Gait3D.json # Uses the same Gait3D.json as Gait3D dataset
  # data_in_use: [true, false]
  num_workers: 1
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: Gait3D-Parsing

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 120000
  save_name: ParsingGait
  eval_func: evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 4
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseParsingCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: ParsingGait
  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    channels: # Layers configuration for automatically model construction
      - 64
      - 128
      - 256
      - 512
    layers: 
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 21
  SeparateBNNecks:
    class_num: 3000
    in_channels: 256
    parts_num: 21
  bin_num:
    - 16
  gcn_cfg:
    fine_parts: 11
    coarse_parts: 5
    only_fine_graph: false
    only_coarse_graph: true
    combine_fine_coarse_graph: false

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 40000
    - 80000
    - 100000
  scheduler: MultiStepLR
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  with_test: True
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 40000
  save_name: ParsingGait
  sync_BN: true
  total_iter: 120000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32 # TripletSampler, batch_size[0] indicates Number of Identity
      - 2 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 10 # min frames number for unfixed traing
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: BaseParsingCuttingTransform
