# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: OUMVLP
  dataset_root: your_path
  dataset_partition: ./misc/partitions/OUMVLP.json
  num_workers: 4
  remove_no_gallery: false
  test_dataset_name: OUMVLP

evaluator_cfg:
  enable_distributed: true
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 210000
  save_name: GaitGL
  sampler:
    batch_size: 8
    sample_type: all_ordered
    type: InferenceSampler

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    margin: 0.2
    type: InfoLoss
    log_prefix: infonce
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true
    log_prefix: softmax

model_cfg:
  model: GaitGL
  channels: [32, 64, 128, 256]
  class_num: 5153


optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  scheduler: CosineLRScheduler
  t_initial: 210000
  lr_min: 1.0e-4
  warmup_t: 4000
  warmup_lr_init: 1.0e-6
  k_decay: 1.0

trainer_cfg:
  enable_distributed: true
  enable_float16: true
  with_test: false
  log_iter: 10
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: GaitGL
  sync_BN: true
  total_iter: 210000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
